server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  profiles:
    active: ${SPRING_APPLICATION_ACTIVE:dev}
  cloud:
    config:
      username: ${CLOUD_CONFIG_USERNAME}
      password: ${CLOUD_CONFIG_PASSWORD}
  config:
    import: optional:configserver:http://${CLOUD_CONFIG_IP}:${CLOUD_CONFIG_PORT}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_SERVER_USERNAME}:${EUREKA_SERVER_PASSWORD}@${EUREKA_SERVER_IP}:${EUREKA_SERVER_PORT}/eureka

actuator:
  username: ${ACTUATOR_USERNAME}
  password: ${ACTUATOR_PASSWORD}

web-client:
  base-url:
    auth: ${AUTH_DOMAIN_URL}