spring:
  application:
    name: item-service
  profiles:
    active: ${SPRING_APPLICATION_ACTIVE:dev}
  cloud:
    config:
      username: ${CLOUD_CONFIG_USERNAME}
      password: ${CLOUD_CONFIG_PASSWORD}
  config:
    import: optional:configserver:http://${CLOUD_CONFIG_IP}:${CLOUD_CONFIG_PORT}

management:
  endpoints:
    web:
      exposure:
        include: health
  server:
    port: 8081